name: Bug report
description: Report a simple bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report. Please keep it concise and reproducible.
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      placeholder: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: Expected outcome.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      placeholder: Actual outcome (include logs if possible).
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "@confik/cli version"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 26 / Windows 11 / Ubuntu 22.04
    validations:
      required: true
